### ISSUE TITLE
Port mismatch to be fixed in testsuite

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/OperationKeyManagement#249]
- ServiceLayer / BasicPart / /v1/list-ltps-and-fcs / Acceptance / Response body completeness
- ServiceLayer / BasicPart / /v1/redirect-topology-change-information / Acceptance / Response body completeness

error: Provides expected properties in configuration class for 'okm-2-0-1-tcp-c-or-1-0-0-000' expected 3000 to equal 3086

Not sure where the value of 3086 comes from. Both list-ltps-and-fcs and GET control-construct list 3000 as the port for 'okm-2-0-1-tcp-c-or-1-0-0-000'

Not sure if this is specific to OKM or AP.

**Comment by IswaryaaS** [comment]
Response body completeness verifies the retrieved values against the input load-file CC. This method is being followed for  checking the current values against the initial values. This mismatch shall be because the mismatch in configuration made in input load-file and configuration made in server/database/load.json while deploying and testing. 

Closing this issue as the fake-ip script has been updated. Kindly reopen the issue if the issue reoccurs.
